#
###################################
# Site wide configuration
####################################
#
title: Adam J. Stanton
email: adamstanton1979@gmail.com
description: A simple and awesome blog theme powered by jekyll.
# the base hostname & protocol for your site
# If your project is placed in https://github.com/yourname/yourname.github.io at master branch
# Then, the 'url' is: http://yourname.github.io
# If your project is placed in another repository as a gh-pages branch, like: https://github.com/yourname/projectname
# Then, the 'url' is: http://yourname.github.io/projectname
url: http://stantona.github.io/blog
  
#
###################################
# Jekyll configuration
####################################
#
markdown:    kramdown
highlighter:  pygments
excerpt_separator: <!--more-->

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Adam J.Stanton
  avatar: avatar.jpg
  job:
  bio: "Writes mostly about software and other things that interest me."
  email: adamstanton1979@gmail.com
  disqus-shortname:
  twitter: adamjonstanton
  github: stantona
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
